Arp multicast support
cablelabs/transparent-security pull request #311
Opened 2020-11-06 06:13 UTC by spisarski

#### What does this PR do?
Fixes #303 
Implement ARP digest for insertion of L2 routes to the NB nodes
Removed the manual table entries into data forward from the lab trial tests.
#### Do you have any concerns with this PR? no
#### How can the reviewer verify this PR? check CI
#### Any background context you want to provide? A step towards TCP support on Tofino
#### Screenshots or logs (if appropriate)
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? no
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? updated the existing ones

2020-11-06 15:39 UTC, RandyLevensalor approved these changes
Looks good

2020-11-06 16:04 UTC, Sanjhana-Jayagopal approved these changes

2020-11-06 17:08 UTC, RandyLevensalor requested changes
Please confirm that the arp tables are being updated on both the client and target inet hosts.

2020-11-10 21:57 UTC, spisarski commented
Run Tofino aggregate build

2020-11-10 22:00 UTC, spisarski commented
Run Tofino aggregate build

2020-11-10 23:20 UTC, spisarski commented
Run Tofino Environment Build

2020-11-11 15:53 UTC, spisarski commented
found a bug, I'll be making a few changes...

2020-11-11 22:20 UTC, Sanjhana-Jayagopal approved these changes

2020-11-12 00:48 UTC, spisarski commented
@RandyLevensalor & @Sanjhana-Jayagopal - This should now be complete. Much more complex than I originally anticipated and learning that mirrored dummy interfaces are not a good choice if you wanna try and use them for anything real.

2020-11-12 18:37 UTC, spisarski commented
@RandyLevensalor & @Sanjhana-Jayagopal - I will be merging by COB today so lemme know if either of you have any objections.

2020-11-12 21:45 UTC, merged