Added ansible script to load pipelines in AE
cablelabs/transparent-security pull request #331
Opened 2020-11-18 16:26 UTC by akadam

Fixes #308 

#### What does this PR do? Automates load pipelines in AE using ansible
#### Do you have any concerns with this PR? No
#### How can the reviewer verify this PR? 
#### Any background context you want to provide? No
#### Screenshots or logs (if appropriate) No
#### Questions:
- Have you connected this PR to the issue it resolves? Yes
- Does the documentation need an update? No
- Does this add new dependencies? No
- Have you added unit or functional tests for this PR? No

2020-11-18 18:00 UTC, spisarski commented
Run Tofino Environment Build

2020-11-18 18:01 UTC, spisarski commented
Run Tofino aggregate build

2020-11-18 18:02 UTC, spisarski commented
Run Tofino lab trial build

2020-11-18 18:05 UTC, spisarski commented
Run Tofino lab trial build

2020-11-18 18:22 UTC, spisarski requested changes
Mostly nits here. You can choose to address the small stuff or not; however, I really would like to ensure that the AMI has the TPS requirements.txt installed into the Python runtime to help save 5-6 min/run

2020-11-18 18:22 UTC, spisarski commented on automation/p4/tofino/variables.tf
> +variable "hcp_ami" {default ="ami-0479d5b8fff8e060f"}
Can you update this image to have the TPS Python dependencies pre-installed for speed?

2020-11-18 18:22 UTC, spisarski commented on playbooks/ae/templates/udp_data_mapping.json.j2
> +{
You may want to rename this file udp_data_mapping.json as this isn't really a template.

2020-11-18 18:22 UTC, spisarski commented on playbooks/ae/setup_ae_elk.yml
> +        body: "{{ lookup('template','udp_data_mapping.json.j2') }}"
You may just want to use the file contents rather than using a template; however, keeping it as-is would give us more flexibility down-the-road.

2020-11-18 18:22 UTC, spisarski commented on playbooks/tofino/setup_nodes-lab_trial.yml
> +
Please remove this line

2020-11-18 18:22 UTC, spisarski commented on playbooks/tofino/setup_nodes-lab_trial.yml
> +
Please remove these lines

2020-11-18 18:24 UTC, spisarski requested changes
Fix CI, see http://snapsci.cablelabs.com:8080/job/transparent-security-tofino-lab-trial/57/console

2020-11-19 14:58 UTC, spisarski requested changes
Please see the comments for why I think things are failing on http://snapsci.cablelabs.com:8080/job/transparent-security-tofino-lab-trial/65/console

2020-11-19 14:58 UTC, spisarski commented on playbooks/ae/setup_ae_elk.yml
> +        path: "{{remote_scripts_dir}}/udp_monitor_def.json"
I believe this should be "{{ trans_sec_dir }}" instead.

2020-11-19 14:58 UTC, spisarski commented on playbooks/ae/setup_ae_elk.yml
> +        src: "{{remote_scripts_dir}}/udp_monitor_def.json"
I believe this should be "{{ trans_sec_dir }}" instead.

2020-11-19 20:19 UTC, akadam commented
Run Tofino Environment Build

2020-11-19 20:19 UTC, akadam commented
Run Tofino aggregate build

2020-11-19 20:19 UTC, akadam commented
Run Tofino lab trial build

2020-11-19 21:06 UTC, spisarski approved these changes
We can optimize that AMI TPS Python installation for lab_trial CI later.

2020-11-19 22:46 UTC, merged