Issue 349
cablelabs/transparent-security pull request #379
Opened 2021-01-08 18:10 UTC by akadam

#### What does this PR do? Fixes #365 
#### Do you have any concerns with this PR? No
#### How can the reviewer verify this PR? Run all-pkt-flood
#### Any background context you want to provide? No
#### Screenshots or logs (if appropriate)
#### Questions:
- Have you connected this PR to the issue it resolves? Yes
- Does the documentation need an update? No
- Does this add new dependencies? No
- Have you added unit or functional tests for this PR?

2021-01-08 19:24 UTC, akadam commented
Run Tofino lab trial build

2021-01-08 19:52 UTC, akadam commented
Run Tofino Environment Build

2021-01-08 19:52 UTC, akadam commented
Run Tofino lab trial build

2021-01-08 20:05 UTC, spisarski approved these changes

2021-01-08 20:29 UTC, spisarski requested changes
I think this will fix CI

2021-01-08 20:29 UTC, spisarski commented on playbooks/scenarios/lab_trial/data_inspection_basic.yml
> +    - name: Set up packet ingestion for all packets on analytics engine
Move this block to the top of pkt-flood.yml

2021-01-08 20:37 UTC, spisarski reviewed
Also should stop espcap.py

2021-01-08 20:37 UTC, spisarski commented on playbooks/scenarios/lab_trial/pkt-flood.yml
> +
We need to stop espcap.py here and a service call would make this very easy.

2021-01-11 15:03 UTC, spisarski approved these changes

2021-01-11 16:22 UTC, merged