Issue 411 doc improvements
cablelabs/transparent-security pull request #417
Opened 2021-08-09 20:44 UTC by spisarski

#### What does this PR do?
Fixes #411 & Fixes #412
Updated, improved, and tested processes identified all docs to reflect the current state of the repository
Added more links in MD docs
Included examples and CRDs for setting up and running a TPS AE running on Kubernetes
#### Do you have any concerns with this PR?
no
#### How can the reviewer verify this PR?
Ensure the docs are accurate...
#### Any background context you want to provide?
We are trying to ready this repository for mothballs so it will be easier to reconstitute down-the-road
#### Screenshots or logs (if appropriate)
#### Questions:
- Have you connected this PR to the issue it resolves? yes
- Does the documentation need an update? yes
- Does this add new dependencies? no
- Have you added unit or functional tests for this PR? no

2021-08-09 20:49 UTC, spisarski commented
Run Tofino lab trial build

2021-08-09 21:28 UTC, spisarski commented
Run Tofino aggregate build

2021-08-10 14:00 UTC, chriscorcimiglia requested changes
Looking good. I made some comments that you should be able to address pretty easily. Thanks for pulling all of this together!

2021-08-10 14:31 UTC, spisarski commented on docs/ae/SIDDHI_AE_SETUP.md
> +  ([installed based on these instructions](https://www.digitalocean.com/community/tutorials/how-to-install-apache-kafka-on-ubuntu-20-04)
Actually added the left paren on accident

2021-08-16 14:00 UTC, chriscorcimiglia approved these changes

2021-08-18 14:06 UTC, merged